name: Add Journal
description: Submit a journal to be added to the DH Journals list
title: "[Add Journal]: "
labels: ["new-journal"]
body:
  - type: markdown
    attributes:
      value: |
        ## Add a new journal to the DH Journals list
        Please provide the information below for the journal you want to add.
        
        **Note:** To add multiple journals, please submit a separate issue for each journal.

  - type: input
    id: journal_url
    attributes:
      label: Journal URL
      description: Provide the URL of the journal website
      placeholder: https://example.com/journal
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### DH Level Definitions
        
        - **Exclusively**: The journal is completely devoted to publishing Digital Humanities articles
        - **Significantly**: A significant set of publications deal with Digital Humanities
        - **Marginally**: Only a small set of publications are Digital Humanities
        - **Mega-journal**: Large multidisciplinary journals that may include some DH content

  - type: dropdown
    id: journal_dh_level
    attributes:
      label: DH Level
      description: Select the Digital Humanities level for this journal (journals will be ordered by this level, then alphabetically by title)
      options:
        - Exclusively
        - Significantly
        - Marginally
        - Mega-journal
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any additional context or information about the journal
      placeholder: Optional notes about the journal
    validations:
      required: false
